apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Synced by the per-team Flux GitRepository/Kustomization "baburciu"
# (created by the workload-team-defs chart) into namespace swct-baburciu.
resources:
- wc-rocket.yaml
